version: '3.8'
services:
  web:
    build: .
    ports:
      - "8500:8500"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/claimprocess
  db:
    image: postgres:13
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: claimprocess
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  tests:
      build: .
      depends_on:
        - web
        - db
      environment:
        - DATABASE_URL=postgresql://user:password@db/claimprocess
      command: pytest -v
